### ISSUE TITLE
VHCI Error on Windows 10

### ISSUE THREAD

**Issue by abbascankk** [cezuni/usbip-win#11]
usbip: error: open vhci driver
usbip: error: failed to read: err:6

What i do ?

**Comment by abbascankk** [comment]
SDK and WDK correct but my windows version is 1809

**Comment by cezuni** [comment]
Can you check a vhci driver to be loaded correctly? In that case, your error may happen.

**Comment by abbascankk** [comment]
i do everything on document but i get this vhci error.

**Comment by yelfarri** [comment]
@abbascankk can you explain your setup? Which steps did you follow?
 logs files and maybe pictures on how the device manager looks like?  
Did #6  take a look on the following issues, in the end, I wrote a small comment on the steps that are needed..

**Comment by cezuni** [comment]
stub driver makes your windows act as usbip server. You need to install vhci if you want windows to be an usbip client.

**Comment by abbascankk** [comment]
i know i install all inf but nothing in device manager

**Comment by cezuni** [comment]
@abbascankk : It's weird.. I have both drivers tested on win 10(1607). May your Win 10(1809) be a issue? For clarity, let me ask: What type usbip-win did you try ? usbip server or usbip client ?

**Comment by abbascankk** [comment]
let me explain my winver is 1809 latest version sdk and driver pack is correct i export certificate and install all driver inf to my device manager USIP stub is ok but i cant see vhci driver on there so client is windows and server is my computer i try the other computer for connect me its getting this error and my server is crashing as well i get this error on client : usbip: error: open vhci driver
usbip: error: failed to read: err:6

server is crashes without error like ctrl + c

**Comment by abbascankk** [comment]
im going download 1603 now for the server

**Comment by abbascankk** [comment]
ok i read all of them again and i see my problem i cant open test signing on client side this is may be error i will try soon

**Comment by yelfarri** [comment]
@abbascankk did you solve it ? Can you please write @USERNAME so i see you it is addressed to me :). I mostly reply based on notifications :)

**Comment by HoudayerPierre** [comment]
Same error for me with a Windows client and linux server.
I can see in the device manager under "system devices" one "USB/IP VHCI" and in the events, nothing bad.
(Used the .inf from pre-release 0.0.1 because from the 0.0.4 it can't be installed)

**Comment by WyntrHeart** [comment]
Hello. Same issue here on Win10 1809 and 1803 client. I installed the latest release version of your USB/IP following the steps in the readme. The driver installed and I was able to see my usb device with the list command, but I received the same error described above when I attempted to attach my device. In Device Manager I can see the "USB/IP VHCI" device listed, but it has a warning saying:

     "Windows cannot verify the digital signature for the drivers required for this device. A recent hardware or software change might have installed a file that is signed incorrectly or damaged, or that might be malicious software from an unknown source. (Code 52)"

The problem is exactly the same on my laptop (with Win10, 1803) and my desktop (1809). And idk if it makes any difference but the server is running on an Android 8.0 phone and the USB device is an ATARI 2600 joystick USB adapter (with a controller connected).

**Comment by WyntrHeart** [comment]
Nevermind, I found the issue. I missed a step and didn't enable test signing. It's working now.

**Comment by HoudayerPierre** [comment]
@WyntrHeart, Did you still have the error when you create a connection with a remote usb device ?
(My "USB/IP VHCI" device listed and **without** a warning sign)

**Comment by cezuni** [comment]
Old & inactive issue. I'll close.
