### ISSUE TITLE
usbip server on Win

### ISSUE THREAD

**Issue by igoryonya** [cezuni/usbip-win#13]
Your readme explains installation of server on linux, but I thought, that your port is for windows.
Can I use usbip server on windows?

**Comment by cezuni** [comment]
> Your readme explains installation of server on linux, but I thought, that your port is for windows.

INSTALL section in readme consists of 2 parts: USBIP server & client.

> Can I use usbip server on windows?

Sure, you can. usbip server on windows was the first motivation to start this repo.

**Comment by igoryonya** [comment]
Do I have to compile it with VC++, or can I compile it with GCC or Ming?

**Comment by cezuni** [comment]
I had compiled with Visual studio 2017. Detailed build environment is presented in readme. Other build tools are not tried yet. You can be a pioneer. :)
