### ISSUE TITLE
usbipd project build failed

### ISSUE THREAD

**Issue by reclock** [cezuni/usbip-win#26]
I used VS2017 to compile USBip-win.sln, but the usbipd project failed to compile：

usbip_common.lib(usbip_common.obj) : error LNK2001: Unparsable external symbols __acrt_iob_func
1>usbip_common.lib(usbip_setupdi.obj) : error LNK2001: Unparsable external symbols _acrt_iob_func
1>usbip_common.lib(usbip_forward.obj) : error LNK2001: Unparsable external symbols __acrt_iob_func
1>usbip_common.lib(names.obj) : error LNK2001: Unparsable external symbols __acrt_iob_func
1>usbipd_sock.obj : error LNK2001: Unparsable external symbols __acrt_iob_func
1>usbipd_stub.obj : error LNK2001: Unparsable external symbols __acrt_iob_func
1>usbip_common.lib(usbip_network.obj) : error LNK2001: Unparsable external symbols __acrt_iob_func
1>usbip_common.lib(usbip_windows.obj) : error LNK2001: Unparsable external symbols __acrt_iob_func
>usbipd_sock.obj : error LNK2001: Unparsable external symbols __stdio_common_vfprintf
1>usbipd_stub.obj : error LNK2001: Unparsable external symbols  __stdio_common_vfprintf
1>usbip_common.lib(usbip_network.obj) : error LNK2001: Unparsable external symbols  __stdio_common_vfprintf
1>usbip_common.lib(usbip_windows.obj) : error LNK2001: Unparsable external symbols  __stdio_common_vfprintf

**Comment by cezuni** [comment]
@reclock : Sorry for late. Is your issue solved?
