### ISSUE TITLE
run project windows Error

### ISSUE THREAD

**Issue by reclock** [cezuni/usbip-win#27]
I run this project:
server: Windows7
**usbip.exe bind -b 1-136**   //success
**usbipd.exe -b -4**               //success

client: Windows10
**usbip.exe attach -r 192.168.14.129 -b 1-136** //success
![image](https://user-images.githubusercontent.com/23696606/56332127-aff28600-61c1-11e9-95cb-136fa4feca32.png)

But the USB device I saw in the human interface device was abnormal.
![image](https://user-images.githubusercontent.com/23696606/56332136-b84ac100-61c1-11e9-8782-2e65c7b750de.png)

What's the problem?

**Comment by cezuni** [comment]
@reclock : Something goes wrong when a vhci driver sets up a virtual usbip device. But it's impossible to resolve your problem without windows kernel logs. Could you share kernel logs?

**Comment by reclock** [comment]
![image](https://user-images.githubusercontent.com/23696606/56342515-cb25bb80-61ea-11e9-9b69-4c1df2e7d80e.png)

what`s the problem?  i change one computer

**Comment by reclock** [comment]
I use win10 as  server, use win7 as client,   run success, thanks.

**Comment by reclock** [comment]
I want to implement a local virtual USB device based on this project. I don't need to insert a USB device into the server. Do you know of any other similar open source projects? thanks.

**Comment by cezuni** [comment]
@reclock : How about libusb-win32?
Anyway, your issue has been fulfilled. I'll close it.
