### ISSUE TITLE
Multi interface devices with endpoint-less interfaces fail 

### ISSUE THREAD

**Issue by dontech** [cezuni/usbip-win#29]

**Comment by dontech** [comment]
Pull request here: https://github.com/cezuni/usbip-win/pull/28

Probably affects most audio and video devices, as they often have interfaces with no endpoints.

There is no work-around from the client side that will fix this.
Please review and apply the patch.

Thanks,

/pedro

**Comment by dontech** [comment]
Without this most or all of the endpoints will not be detected, and no packets can be sent to/from them.

**Comment by cezuni** [comment]
@dontech : Thanks for your patch. #28 is merged.
