### ISSUE TITLE
usbip: error: tcp connect on attach from Win10 to Ubuntu 14.04 usbipd device

### ISSUE THREAD

**Issue by bmoore27** [cezuni/usbip-win#3]
Testing usbip-win on Windows 10 (1607) connecting to a USB Mass Storage class device hosted from Ubuntu Linux 14.04. I am able to attach I get `usbip: error: tcp connect` when attempting `usbip.exe attach -r 192.168.1.100 -b 5-2`.

The firewall is open on both devices and they are on the same LAN.

**Comment by cezuni** [comment]
The version of usbip in ubuntu 14.4(kernel 4.4.x) is 1.0.0 but 
this usbip-win version is 1.1.1 (USBIP_VERSION: 0x000111)
Your problem seems to be related with version mismatch.
