### ISSUE TITLE
Certificate loading failure

### ISSUE THREAD

**Issue by zhLoser01** [cezuni/usbip-win#32]
win7×64
usbip:error:cannot load certificate:subject: USBIP Test

**Comment by zhLoser01** [comment]
- 
![image](https://user-images.githubusercontent.com/23304686/56948844-f225ab00-6b63-11e9-801e-daa13f3d1471.png)

-

**Comment by zhLoser01** [comment]
![image](https://user-images.githubusercontent.com/23304686/56948954-4c267080-6b64-11e9-99ea-97e04d36cb46.png)

**Comment by cezuni** [comment]
@zhLoser01 : This error means that the certificate cannot be found. Did you install the certificate on local machine registry? (not current user registry) If not, please refer to [this link](https://docs.microsoft.com/ko-kr/windows-hardware/drivers/install/using-certmgr-to-install-test-certificates-on-a-test-computer).

**Comment by zhLoser01** [comment]
![_20190430185902](https://user-images.githubusercontent.com/23304686/56957550-1f7d5380-6b7a-11e9-9e0d-cdd830d0eb54.png)
I can find the header file

**Comment by zhLoser01** [comment]
ok

**Comment by zhLoser01** [comment]
![image](https://user-images.githubusercontent.com/23304686/57187447-76d84680-6f21-11e9-8b25-edafe9c87e8e.png)

**Comment by zhLoser01** [comment]
@cezuni I compiled it in my vs2017+win10 environment, and then ported it to the win7 environment, reporting this error "usbip:error:SignerSignEx failed.hResult #80092006"
"usbip:error:failed to bind device"

**Comment by cezuni** [comment]
@zhLoser01 : As shown in readme, USBIP Test certificate should be installed into 2 certicate stores: "Trusted Root Certification Authority" and "Trusted Publishers" on local machine (not current user). You can check with certlm.msc. I had checked that bind process generates "error: cannot load certificate: USBIP Test" if a certificate is not installed into "Trusted Root Certification Authority".  When a test certificate is not installed into "Trusted Publishers", "error: failed to update driver: e0000242" message is shown. I have no idea about your case. 😢

**Comment by zhLoser01** [comment]
@cezuni My camera and headphones are not recognized by the driver in windows7

**Comment by cezuni** [comment]
@zhLoser01 : I'm too late?? :smile: 
Please tell your story about signing problem.. Is it solved?

 > My camera and headphones are not recognized by the driver in windows7

Maybe #7 will be a solution.

**Comment by cezuni** [comment]
Close the old issue. If you( @zhLoser01 ) need, reopen it.

**Comment by andrewzli** [comment]
if anyone does have this issue in the future, try running cmd as administrator, that worked for me!
