### ISSUE TITLE
windows7 usbip attach -r 192.xxx.xxx.xxx -b  1-1

### ISSUE THREAD

**Issue by zhLoser01** [cezuni/usbip-win#36]
Client windows7 installed camera and headset driver can not be installed, or blue screen

**Comment by zhLoser01** [comment]
@yelfarri @cezuni  Blue screen will appear when the camera is used Do you know how to solve this problem?

**Comment by cantops** [comment]
@yelfarri 
Use windbg to analyze the blue screen log and post it

**Comment by cezuni** [comment]
@zhLoser01 : Will you try again with the latest usbip-win?
