### ISSUE TITLE
interface claim failed: LIBUSB_ERROR_NOT_FOUND

### ISSUE THREAD

**Issue by CrisBSD** [cezuni/usbip-win#37]
Hi, I'm testing a fingerprint reader (U.are.U® 4500 Fingerprint Reader). I have as client a linux machine with kernel 4.15, but when I try to open the device I get: 

journal: interface claim failed: LIBUSB_ERROR_NOT_FOUND

Am I forgetting some configuration?

**Comment by cezuni** [comment]
@CrisBSD : Have you ever installed [libusb-win](https://github.com/libusb/libusb/wiki/Windows) ? usbip-win does not present such an error.

**Comment by Oxalin** [comment]
@CrisBSD Am I understanding correctly that you are experiencing this error on a Linux machine? If so, you are not reporting your bug at the right place. Otherwise, please be more explicit on your setup.

**Comment by cezuni** [comment]
@CrisBSD : Please reopen it when you need.  Close the old issue silently.
