### ISSUE TITLE
Reattaching problem(Was: usb camera headset The driver can't be installed)

### ISSUE THREAD

**Issue by zhLoser01** [cezuni/usbip-win#38]

**Comment by cezuni** [comment]
@zhLoser01 : Can you provide more information ?

**Comment by zhLoser01** [comment]
@cezuni  Win7 client camera and headset can not be used,Can't find camera and headset driver in windows7 client

**Comment by zhLoser01** [comment]
However, for devices with many endpoints, such as usb camera, usb headset, etc., although it can bind and usbip.exe -a ip 3-6, but the driver under Windows can not be installed, you can see under the device manager. Usb Device Over IP" is an exclamation point. I don't know how to drive such devices

**Comment by zhLoser01** [comment]
@cezuni

**Comment by zhLoser01** [comment]
![%1KPMAFCALE5L8TMEO4$GF1](https://user-images.githubusercontent.com/23304686/59192872-741ee000-8bb6-11e9-9008-ebc442c5bcde.png)

**Comment by zhLoser01** [comment]
this is connecting to a webcam device, error.

**Comment by zhLoser01** [comment]
![image](https://user-images.githubusercontent.com/23304686/59239493-3e204100-8c34-11e9-83d9-9879241b5615.png)
Currently, this hardware device is not connected to the computer. (Code 45)

To correct this problem, reconnect this hardware device to your computer.
@cezuni

**Comment by cezuni** [comment]
@zhLoser01 : Your error in screenshot seems to be re-attaching. The first usbip attach command was working correctly even though you typed Ctrl+C . You should note that attach command in usbip-win executes continuously until a user stops explicitly. This is an usbip-win limitation. Linux usbip attach command completes shortly and gives a prompt. Anyway, re-attaching failure should be checked by me or any volunteer.

**Comment by cezuni** [comment]
I checked that reattaching works. Close this issue.
