### ISSUE TITLE
cannot buil usbip dev

### ISSUE THREAD

**Issue by srhtgryaktuna** [cezuni/usbip-win#39]
I enclosed screen shot. 

I got an error when binded usb id 196
usbip: error: build_udev: invalid devno: 196
usbip: error: walker_edev: cannot build usbip dev

Can you help me please?

![1](https://user-images.githubusercontent.com/10676086/59161731-fba11c00-8aee-11e9-870c-337effa36557.png)
![2](https://user-images.githubusercontent.com/10676086/59161732-fc39b280-8aee-11e9-9d3d-128fcf61cccc.png)
![3](https://user-images.githubusercontent.com/10676086/59161733-fc39b280-8aee-11e9-8b6f-582691b363cf.png)

**Comment by cezuni** [comment]
@srhtgryaktuna : I'm too late. But can you leave any message for the issue?
