### ISSUE TITLE
Ubuntu Server and Windows Client

### ISSUE THREAD

**Issue by doganmurat** [cezuni/usbip-win#4]
Hi @cezuni,

I am looking for a working usb-ip solution.
I need Linux to be server (Kernel V 4.1x) and windows 10 as client.

Is your project suitable for that config?
Did you test any config like that?
Thanks
Best regards

**Comment by dhyanisumit12** [comment]
Hi @doganmurat 
My requirement is same as you mentioned. 
Client on windows 10 and server on Raspberry Pi 3.  But using this library as client it shows 'unknown device ' in device manager with name 'USB Device over IP'. 
If you have solution of the same please share it.
