### ISSUE TITLE
Build with Release configuration

### ISSUE THREAD

**Issue by koudis** [cezuni/usbip-win#40]
Hello all,

I use USBIP client on windows. It works quite fine (except some errors with queue overflow etc.).

I Try to compile USBIP by Release configuration. It fails. Mainly because mishmash between debug and release header/libraries.

My question is - is this behaviour intentionall ot it's a bug. If it's a Bug, may I create PR with repairs? Or it's the subject of further/actual development.

@cezuni  In case of PR - from which branch I can create a PR?

**Comment by cezuni** [comment]
@koudis : Release configuration has not been a main concern. But you are welcome to improve it. master branch would be good for PR.

**Comment by koudis** [comment]
ok, thanks for reply. If the Release configuration is not a main concern I will not create PR for this now (it just complicate development).

But I try to create PR with Toolset update. Just for "make all dependencies actual".

**Comment by cezuni** [comment]
Current usbip-win is able to build with release configuration. (refer #42)
