### ISSUE TITLE
Is there a compiled program download?

### ISSUE THREAD

**Issue by flynaj** [cezuni/usbip-win#5]
There is no compiled program download, I did not start the environment, just want to use this program.

**Comment by cezuni** [comment]
Sadly, there's no compiled one because it's not yet at production level.

**Comment by cezuni** [comment]
I have added usbip-win binaries at [release page](https://github.com/cezuni/usbip-win/releases).

**Comment by builker** [comment]
Really appreciate the pre-built binaries for [usbip-win 0.0.4](https://github.com/cezuni/usbip-win/releases/tag/0.0.4). I like to install the Windows client without creating a build environment. Is that right I need 6 files to do so?

I've found the following 4 files: usbip_test.pfx, usbip.exe, usbip_vhci.sys, usbip_vhci.inf.

Where can I find the other 2 files: usbip_vhci.cer, usbip_vhci.cat?

**Comment by cezuni** [comment]
@builker : You can find those 2 files in [previous release](https://github.com/cezuni/usbip-win/releases/tag/0.0.1).

**Comment by builker** [comment]
Thank you, @cezuni , for your fast response. They are working. :)
