### ISSUE TITLE
Error Installing Driver usbip_vhci.inf

### ISSUE THREAD

**Issue by DanielBorgesOliveira** [cezuni/usbip-win#63]
Hi friends,

I am trying to install the drivers and the device manager return the error:

![Untitled](https://user-images.githubusercontent.com/38186659/63176203-dfa08600-c01b-11e9-8d83-c27831570b72.png)

The OS is Windows 10 Pro x64.

What can I do to resolv this?

I thank you very much.

**Comment by cezuni** [comment]
@DanielBorgesOliveira : Please check the steps in "Windows USB/IP Client" section of README. vhci installation works well. You seemed to miss some installation steps.

**Comment by DanielBorgesOliveira** [comment]
Thank for your reply. I solved the issue compiling the driver from source.
